project:
  type: book
  output-dir: docs

book:
  title: "Hands-On Single-Cell CRISPR Screen Analysis"
  reader-mode: true
  page-footer:
    left: |
      Hands-On Single-Cell CRISPR Screen Analysis was written by Timothy Barry and Eugene Katsevich
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: book_cover.png
  favicon: book_cover.png
  repo-url: https://github.com/timothy-barry/sceptre-book
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - sceptre.qmd
    - import-data.qmd
    - set-analysis-parameters.qmd
    - assign-grnas.qmd
    - run-qc.qmd
    - run-calibration-check.qmd
    - run-power-check-and-discovery-analysis.qmd
  appendices:
    - acknowledgements.qmd
    - glossary.qmd

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Timothy Barry, Eugene Katsevich"

execute:
  cache: true

editor: visual
