project:
  type: book
  output-dir: docs

book:
  title: "Hands-On Single-Cell CRISPR Screen Analysis"
  reader-mode: false
  page-footer:
    left: |
      Hands-On Single-Cell CRISPR Screen Analysis
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: book_cover.png
  favicon: book_cover.png
  repo-url: https://katsevich-lab.github.io/sceptre/
  repo-branch: main
  sidebar:
    logo: hex.jpg
    logo-href: https://katsevich-lab.github.io/sceptre/
  chapters:
    - index.qmd
    - sceptre.qmd

    - part: Part I. Introduction to sceptre
      chapters:
        - import-data.qmd
        - set-analysis-parameters.qmd
        - assign-grnas.qmd
        - run-qc.qmd
        - run-calibration-check.qmd
        - run-power-check-and-discovery-analysis.qmd

    - part: Part II. At-scale sceptre
      chapters:
        - at-scale.qmd

    - part: Part III. Methods and algorithms

  appendices:
    - glossary.qmd
    - faq.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Timothy Barry, Eugene Katsevich"
    after_body: "iframeHandler.js"
    css: custom.css

execute:
  cache: true

editor: visual
