project:
  type: book
  output-dir: docs

book:
  title: "Applied Single-Cell CRISPR Screen Data Analysis: A Guide Using `sceptre` and R"
  reader-mode: true
  page-footer:
    left: |
      Applied Single-Cell CRISPR Screen Data Analysis was written by Timothy Barry and Eugene Katsevich
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: book_cover.png
  favicon: book_cover.png
  repo-url: https://github.com/timothy-barry/sceptre-book
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - sceptre.qmd
    - import-data.qmd
    - set-analysis-parameters.qmd
    - assign-grnas.qmd
    - run-qc.qmd
    - run-calibration-check.qmd

format:
  html:
    theme: cosmo
    code-link: true
    author-meta: "Timothy Barry, Eugene Katsevich"

execute:
  cache: true

editor: visual
